### ISSUE TITLE
Need exhaustive test coverage for the scheduler service.

### ISSUE THREAD

**Issue by lbdm44** [ember-app-scheduler/ember-app-scheduler#14]
At the current moment, there is very minimal test coverage for the scheduler service.

The title says it all.

**Comment by scalvert** [comment]
I'm working on a larger refactoring that should help address this.

**Comment by runspired** [comment]
Factor the factors plz

**Comment by scalvert** [comment]
As of 1.0, the scheduler service has been deprecated. An extensive suite of tests is verifying the new behavior. Closing this as a result.
