### ISSUE TITLE
Currently released package not merged into master branch

### ISSUE THREAD

**Issue by ef4** [ember-app-scheduler/ember-app-scheduler#151]
I was confused for a while because the currently released version (1.0.4) is not merged to master. I found it on the ts-conversion branch.

If ts-conversion is really supposed to be the default branch, you can set that in github settings.

**Comment by rwjblue** [comment]
The code from `ts-conversion` is merged into `master` branch (see #123). I don't think the version bump and tag was pushed though...

**Comment by ef4** [comment]
I see. It's because the tagged release commit isn't on either branch.

```
$ git log --oneline ts-conversion..v1.0.4
0c9688f (tag: v1.0.4) 1.0.4
4242e5d Merge branch 'master' of https://github.com/ember-app-scheduler/ember-app-scheduler
679f2d5 Merge branch 'master' of https://github.com/ember-app-scheduler/ember-app-scheduler
e82d21c (tag: v1.0.3) 1.0.3

$ git log --oneline master..v1.0.4
0c9688f (tag: v1.0.4) 1.0.4
4242e5d Merge branch 'master' of https://github.com/ember-app-scheduler/ember-app-scheduler
679f2d5 Merge branch 'master' of https://github.com/ember-app-scheduler/ember-app-scheduler
e82d21c (tag: v1.0.3) 1.0.3
```

**Comment by rwjblue** [comment]
Ya, exactly. I think @scalvert needs to do:

```
git fetch
git checkout master
git reset --hard origin/master
git merge v1.0.4
```

**Comment by scalvert** [comment]
Well, this basically keeps my streak of borking up repos. Will fix.

**Comment by scalvert** [comment]
Fixed. Thanks, @ef4!
