### ISSUE TITLE
Garbage files in npm package

### ISSUE THREAD

**Issue by san650** [ember-app-scheduler/ember-app-scheduler#16]
I've installed ember-app-scheduler v0.2.1 and it seems that there are some unneeded files and folders in the package

```
.node_modules.ember-try/
package.json.ember-try
yarn.lock
```

<img width="609" alt="v0 2 1" src="https://user-images.githubusercontent.com/1234607/32460626-25a52222-c312-11e7-8642-56ed1721731d.png">

**Comment by rwjblue** [comment]
Awesome, thank you for reporting!

**Comment by scalvert** [comment]
Thanks for reporting this. We'll be removing these for the latest release, which I anticipate will be soon!

**Comment by scalvert** [comment]
Fixed in v0.2.2. Will also be fixed in the upcoming version of v1.0.0
