### ISSUE TITLE
Seeing race conditions in tests due to waiter

### ISSUE THREAD

**Issue by kratiahuja** [ember-app-scheduler/ember-app-scheduler#17]
We are seeing our tests randomly failing after using `ember-app-scheduler` for one of our tests. The error message is: `TypeError: Cannot read property 'afterContentPaint' of null`.

After looking into the stack trace, it seems to be occurring at this line: https://github.com/sreedhar7/ember-app-scheduler/blob/master/addon/services/scheduler.js#L71 where `this.queues` is null. In testing mode it seems, `this.queues` can be null per the check here: https://github.com/sreedhar7/ember-app-scheduler/blob/master/addon/services/scheduler.js#L185

It seems in `willDestroy` we releasing `this.queues` itself. 

Shouldn't the `init` [here](https://github.com/sreedhar7/ember-app-scheduler/blob/master/addon/services/scheduler.js#L174) initialize the queues? 

Is there a better way to fix this issue? Or is it something wrong with our tests or usage? 

cc: @scalvert

**Comment by scalvert** [comment]
I believe #15 was attempting to address this. It's close but there's a few changes that need to be made before it can land.

**Comment by scalvert** [comment]
I believe that the rewrite of the app-scheduler in functional form should address this. See #26

**Comment by scalvert** [comment]
As of 1.0, the test waiter has totally changed, and as such you shouldn't experience this race anymore (we don't employ queues, or have interleaved timing issues). Closing this as a result.
