### ISSUE TITLE
Instance Initializer unused?

### ISSUE THREAD

**Issue by snewcomer** [ember-app-scheduler/ember-app-scheduler#20]
👋 

I was wondering what the use case for [this](https://github.com/sreedhar7/ember-app-scheduler/blob/master/addon/instance-initializers/init-app-scheduler.js) instance-initializer was?  Is it possible to remove?

**Comment by scalvert** [comment]
The instance initializer will be removed with the latest version, which is essentially a rewrite of the scheduler in functional form.

**Comment by scalvert** [comment]
As of 1.0 of the app-scheduler, the initializer isn't used anymore and has been removed. I'm closing this as a result.
