### ISSUE TITLE
Could not find module `ember-app-scheduler` imported from `ember-router-scroll/index`

### ISSUE THREAD

**Issue by czosel** [ember-app-scheduler/ember-app-scheduler#261]
I've been debugging why the CI build with `--no-lockfile` of `ember-cli-addon-docs` is failing (see [the logfile here](https://travis-ci.org/ember-learn/ember-cli-addon-docs/jobs/510279745)) - and it seems that the latest release `v.1.0.7` causes this issue. When I use the current master instead, the problem disappears.
If I'm not missing anything, releasing a new version would fix the issue. 

Thanks in advance!

**Comment by scalvert** [comment]
Hey @czosel, you're totally right. I was working on converting `ember-app-scheduler` to use `ember-cli-addon-doc`, which led to a number of other updates. In the process, I borked master. I fixed it, and merged it (while in my car commuting home), but didn't get a chance to release. Doing that now.

Sorry for the long story, and the inconvenience!

**Comment by czosel** [comment]
Hi @scalvert, no worries at all! My build is green again, thanks for your quick reaction! :+1:

**Comment by scalvert** [comment]
My pleasure!
