### ISSUE TITLE
`.node_modules.ember-try` included in ember-app-scheduler@0.2.1

### ISSUE THREAD

**Issue by Turbo87** [ember-app-scheduler/ember-app-scheduler#29]
see https://unpkg.com/ember-app-scheduler@0.2.1/

**Comment by scalvert** [comment]
Thanks, @Turbo87! I saw this, and will ensure it's removed in the latest version.

**Comment by Turbo87** [comment]
@scalvert is there a timeline for that release? I just had to `yarn install` on a train and downloading `ember-app-scheduler` took about 20min... :-/

**Comment by scalvert** [comment]
:(

I'm publishing v0.2.2 right now. Sorry for this!

**Comment by scalvert** [comment]
Fixed as v0.2.2
