### ISSUE TITLE
Convert test waiter to new waiter style in @ember/test-helpers 1.6.0

### ISSUE THREAD

**Issue by scalvert** [ember-app-scheduler/ember-app-scheduler#352]
We should convert the test waiter to the new style used in `@ember/test-helpers` 1.6.0. This style uses `ember-test-waiters` APIs to begin/end the waiter.

**Comment by scalvert** [comment]
I believe we'd need to add a peer dependency on that version of `@ember/test-helpers`

**Comment by rwjblue** [comment]
@scalvert - Lets make `ember-test-waiter` polyfill for us, so we don't have a hard dependency on `@ember/test-helper@1.6.0`.

**Comment by scalvert** [comment]
I'm open to this, but think it's a bit of a burden to have to reimplement the `ember-test-waiter` APIs using the older APIs. It'd be nicer to keep that code clean. We can, of course, conditionally do this based on version at build time. 

What did you have in mind?
