### ISSUE TITLE
Could not find module ember-test-waiters imported from ember-app-scheduler/scheduler

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-app-scheduler/ember-app-scheduler#712]
Ran in to this (again?):

![image](https://user-images.githubusercontent.com/199018/83257147-bfdce780-a181-11ea-9cb0-eee6d0c07d02.png)
```
"Error
    at Backburner.scheduleOnce (https://localhost:4201/assets/vendor.js:57443:32)
    at once (https://localhost:4201/assets/vendor.js:41440:23)
    at App.advanceReadiness (https://localhost:4201/assets/vendor.js:35169:27)
    at App._bootSync (https://localhost:4201/assets/vendor.js:35230:14)
    at App.domReady (https://localhost:4201/assets/vendor.js:35120:12)
    at invoke (https://localhost:4201/assets/vendor.js:56976:16)
    at Queue.flush (https://localhost:4201/assets/vendor.js:56867:13)
    at DeferredActionQueues.flush (https://localhost:4201/assets/vendor.js:57064:21)
    at Backburner._end (https://localhost:4201/assets/vendor.js:57598:34)
    at Backburner._boundAutorunEnd (https://localhost:4201/assets/vendor.js:57267:14)"
```
that probs isn't that helpful,
but, where is the ember-app-scheduler dep specified? 

My app has `ember-app-scheduler@4.0.1`, which looks like the latest :-\ (since that release there have only been 4 or so pages of dependabot updates ;) )

**Comment by NullVoxPopuli** [comment]
ok, this looks like a yarn / resolutions issue? 

the only other package with ember-test-waiters is @ember/test-helpers@1.7.1 (with `ember-test-waiters@1.2.0`), and I guess they were conflicting.

Adding `"ember-test-waiters": "2.1.1"` to `resolutions` in package.json fixes the above error.

**Comment by NullVoxPopuli** [comment]
but maybe it still is a "monorepo" problem? idk. it's super weird.

If I stick a resolutions entry in my yarn-workspaces root package.json, specifying ember-test-waiters 2.1.1, everything is fine. :-\
seems weird. yarn bug? idk

**Comment by rwjblue** [comment]
Likely just how lock files work. This doesn't look like a new bug (seems like the one that @scalvert fixed in https://github.com/emberjs/ember-test-waiters/pull/148). 

In theory, this package could update its minimum version (which it did in #703) and release to ensure none of its consumers are affected (if they update to that new version).

**Comment by NullVoxPopuli** [comment]
I ran in to this again today over on: 
https://github.com/NullVoxPopuli/emberclear/pull/919
deployed at https://5edbaff5787452f7d757532b--emberclear.netlify.app/

after running 
```
# note: monorepo/yarn-workspaces
find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +" # recursively delete node_modules
git checkout master -- yarn.lock && yarn && npx yarn-deduplicate && yarn && cd emberclear && yarn start # dev server
```

and that got rid of the error :shrug:

**Comment by scalvert** [comment]
@NullVoxPopuli sorry you keep running into issues with `ember-test-waiters`. I've been trying to move the package forward towards publishing as `@ember/test-waiters`, but along the way I've introduced a few bugs related to published types and module resolutions. I'm hoping they're mostly resolved at this point, but please let us know if they aren't.

It looks like you've been our guinea pig, so thanks for that!

**Comment by NullVoxPopuli** [comment]
I end up being the guinea pig for a lot of things, it's cool ❤️ 
It helps that all my testing of this stuff isn't on anything that I need to make money.
