### ISSUE TITLE
Use RouterService instead of the main Router

### ISSUE THREAD

**Issue by buschtoens** [ember-app-scheduler/ember-app-scheduler#772]
Looking at the code for `setupRouter(router)`, it _looks_ like we could also just use the [`RouterService`](https://api.emberjs.com/ember/release/classes/RouterService) in newer apps, as it also supports the `routeWillChange` & `routeDidChange` events by now.

https://github.com/ember-app-scheduler/ember-app-scheduler/blob/c3fa662785bd23f966634de66d65b5904bd336e8/addon/scheduler.ts#L59-L79

I think this would be a bit cleaner, as directly hooking into the main `Router` feels slightly off to me. It would also allow us to set this up automatically via an instance initializer, in case this is something we'd want.

I'm curious what you think. 🙂

**Comment by scalvert** [comment]
@buschtoens, I really like this "hands-off" configuration approach. Honestly, I'm not sure why we didn't think of this before!

I'm supportive of making app scheduler easier to use. Thanks for this.

**Comment by SergeAstapov** [comment]
Isn't this completed already? There is even [a deprecation for that](https://github.com/ember-app-scheduler/ember-app-scheduler/blob/b275989b19581266aa490e6d5cd936aa97abf613/addon/scheduler.ts#L83)
