### ISSUE TITLE
Erroneous deprecation warning?

### ISSUE THREAD

**Issue by gzurbach** [ember-app-scheduler/ember-app-scheduler#956]
Hi there,

I think there might be an issue with a deprecation warning recently added here:
https://github.com/ember-app-scheduler/ember-app-scheduler/blob/master/addon/scheduler.ts#L84

The second parameter of `deprecate()` is documented as follow:
> If **falsy**, the deprecation will be displayed.

Therefore, I wonder if `router instanceof Router` should instead be `!(router instanceof Router)` or `router instanceof RouterService`. 

When looking at the code in my debugger console, the code looks like this:
```js
(true && !(router instanceof Ember.Router) && Ember.deprecate('The use of Ember.Router in setupRouter is deprecated. Please use the router service.', router instanceof Ember.Router, {
  id: 'ember-app-scheduler.setupRouter',
  until: '6.0.0'
}));
```

Related issue: https://github.com/DockYard/ember-router-scroll/issues/271

I am not familiar with Ember deprecations, so apologies if I am mistaken :)

**Comment by rwwagner90** [comment]
This definitely seems correct to me. We're getting a bunch of these deprecation warnings from ember-router-scroll.

**Comment by rwjblue** [comment]
Eeck. Ya, anyone have a chance to send a PR?

**Comment by rwjblue** [comment]
I think this was introduced in https://github.com/ember-app-scheduler/ember-app-scheduler/pull/773

/cc @buschtoens @scalvert
